export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const INGREDIENT_MODEL = 'INGREDIENT_MODEL';
export const PRODUCT_MODEL = 'PRODUCT_MODEL';
export const USER_MODEL = 'USER_MODEL';
export const ORDER_MODEL = 'ORDER_MODEL';
